##static currencies
UPDATE static_currencies SET cu_name_sv='UAE-dirham', cu_sub_name_sv='' WHERE cu_iso_3='AED';
UPDATE static_currencies SET cu_name_sv='Afghani', cu_sub_name_sv='' WHERE cu_iso_3='AFN';
UPDATE static_currencies SET cu_name_sv='Lek', cu_sub_name_sv='' WHERE cu_iso_3='ALL';
UPDATE static_currencies SET cu_name_sv='Dram', cu_sub_name_sv='' WHERE cu_iso_3='AMD';
UPDATE static_currencies SET cu_name_sv='Antiller gulden', cu_sub_name_sv='' WHERE cu_iso_3='ANG';
UPDATE static_currencies SET cu_name_sv='Kwanza', cu_sub_name_sv='' WHERE cu_iso_3='AOA';
UPDATE static_currencies SET cu_name_sv='Argentinsk peso', cu_sub_name_sv='' WHERE cu_iso_3='ARS';
UPDATE static_currencies SET cu_name_sv='Australisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='AUD';
UPDATE static_currencies SET cu_name_sv='Arubansk florin', cu_sub_name_sv='' WHERE cu_iso_3='AWG';
UPDATE static_currencies SET cu_name_sv='Azerbajdzjansk manat', cu_sub_name_sv='' WHERE cu_iso_3='AZN';
UPDATE static_currencies SET cu_name_sv='Konvertibilna marka', cu_sub_name_sv='' WHERE cu_iso_3='BAM';
UPDATE static_currencies SET cu_name_sv='Barbadisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='BBD';
UPDATE static_currencies SET cu_name_sv='Taka', cu_sub_name_sv='' WHERE cu_iso_3='BDT';
UPDATE static_currencies SET cu_name_sv='Lev', cu_sub_name_sv='' WHERE cu_iso_3='BGN';
UPDATE static_currencies SET cu_name_sv='Bahrainsk dinar', cu_sub_name_sv='' WHERE cu_iso_3='BHD';
UPDATE static_currencies SET cu_name_sv='Burundisk franc', cu_sub_name_sv='' WHERE cu_iso_3='BIF';
UPDATE static_currencies SET cu_name_sv='Bermudisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='BMD';
UPDATE static_currencies SET cu_name_sv='Bruneisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='BND';
UPDATE static_currencies SET cu_name_sv='Boliviano', cu_sub_name_sv='' WHERE cu_iso_3='BOB';
UPDATE static_currencies SET cu_name_sv='Bolivian Mvdol (fonder)', cu_sub_name_sv='' WHERE cu_iso_3='BOV';
UPDATE static_currencies SET cu_name_sv='Real', cu_sub_name_sv='' WHERE cu_iso_3='BRL';
UPDATE static_currencies SET cu_name_sv='Bahamansk dollar', cu_sub_name_sv='' WHERE cu_iso_3='BSD';
UPDATE static_currencies SET cu_name_sv='Ngultrum', cu_sub_name_sv='' WHERE cu_iso_3='BTN';
UPDATE static_currencies SET cu_name_sv='Pula', cu_sub_name_sv='' WHERE cu_iso_3='BWP';
UPDATE static_currencies SET cu_name_sv='Vitrysk rubel', cu_sub_name_sv='' WHERE cu_iso_3='BYR';
UPDATE static_currencies SET cu_name_sv='Belizisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='BZD';
UPDATE static_currencies SET cu_name_sv='Kanadensisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='CAD';
UPDATE static_currencies SET cu_name_sv='Kongolesisk franc', cu_sub_name_sv='' WHERE cu_iso_3='CDF';
UPDATE static_currencies SET cu_name_sv='WIR euro (alternativ valuta)', cu_sub_name_sv='' WHERE cu_iso_3='CHE';
UPDATE static_currencies SET cu_name_sv='Schweizisk franc', cu_sub_name_sv='' WHERE cu_iso_3='CHF';
UPDATE static_currencies SET cu_name_sv='WIR franc (alternativ valuta)', cu_sub_name_sv='' WHERE cu_iso_3='CHW';
UPDATE static_currencies SET cu_name_sv='Unidad de Fomento (fonder)', cu_sub_name_sv='' WHERE cu_iso_3='CLF';
UPDATE static_currencies SET cu_name_sv='Chilensk peso', cu_sub_name_sv='' WHERE cu_iso_3='CLP';
UPDATE static_currencies SET cu_name_sv='Renminbi', cu_sub_name_sv='' WHERE cu_iso_3='CNY';
UPDATE static_currencies SET cu_name_sv='Colombiansk peso', cu_sub_name_sv='' WHERE cu_iso_3='COP';
UPDATE static_currencies SET cu_name_sv='Unidad de Valor Real', cu_sub_name_sv='' WHERE cu_iso_3='COU';
UPDATE static_currencies SET cu_name_sv='Colón', cu_sub_name_sv='' WHERE cu_iso_3='CRC';
UPDATE static_currencies SET cu_name_sv='Kubansk peso', cu_sub_name_sv='' WHERE cu_iso_3='CUP';
UPDATE static_currencies SET cu_name_sv='Kapverdisk escudo', cu_sub_name_sv='' WHERE cu_iso_3='CVE';
UPDATE static_currencies SET cu_name_sv='Tjeckisk koruna', cu_sub_name_sv='' WHERE cu_iso_3='CZK';
UPDATE static_currencies SET cu_name_sv='Djiboutisk franc', cu_sub_name_sv='' WHERE cu_iso_3='DJF';
UPDATE static_currencies SET cu_name_sv='Dansk krone', cu_sub_name_sv='' WHERE cu_iso_3='DKK';
UPDATE static_currencies SET cu_name_sv='Dominikansk peso', cu_sub_name_sv='' WHERE cu_iso_3='DOP';
UPDATE static_currencies SET cu_name_sv='Algerisk dinar', cu_sub_name_sv='' WHERE cu_iso_3='DZD';
UPDATE static_currencies SET cu_name_sv='Kroon', cu_sub_name_sv='' WHERE cu_iso_3='EEK';
UPDATE static_currencies SET cu_name_sv='Egyptiskt pund', cu_sub_name_sv='' WHERE cu_iso_3='EGP';
UPDATE static_currencies SET cu_name_sv='Nakfa', cu_sub_name_sv='' WHERE cu_iso_3='ERN';
UPDATE static_currencies SET cu_name_sv='Birr', cu_sub_name_sv='' WHERE cu_iso_3='ETB';
UPDATE static_currencies SET cu_name_sv='Euro', cu_sub_name_sv='' WHERE cu_iso_3='EUR';
UPDATE static_currencies SET cu_name_sv='Fijidollar', cu_sub_name_sv='' WHERE cu_iso_3='FJD';
UPDATE static_currencies SET cu_name_sv='Falklandspund', cu_sub_name_sv='' WHERE cu_iso_3='FKP';
UPDATE static_currencies SET cu_name_sv='Pound sterling', cu_sub_name_sv='' WHERE cu_iso_3='GBP';
UPDATE static_currencies SET cu_name_sv='Lari', cu_sub_name_sv='' WHERE cu_iso_3='GEL';
UPDATE static_currencies SET cu_name_sv='Ghana Cedi', cu_sub_name_sv='' WHERE cu_iso_3='GHC';
UPDATE static_currencies SET cu_name_sv='Gibraltarpund', cu_sub_name_sv='' WHERE cu_iso_3='GIP';
UPDATE static_currencies SET cu_name_sv='Dalasi', cu_sub_name_sv='' WHERE cu_iso_3='GMD';
UPDATE static_currencies SET cu_name_sv='Guinesisk franc', cu_sub_name_sv='' WHERE cu_iso_3='GNF';
UPDATE static_currencies SET cu_name_sv='Quetzal', cu_sub_name_sv='' WHERE cu_iso_3='GTQ';
UPDATE static_currencies SET cu_name_sv='Guyansk dollar', cu_sub_name_sv='' WHERE cu_iso_3='GYD';
UPDATE static_currencies SET cu_name_sv='Hongkongdollar', cu_sub_name_sv='' WHERE cu_iso_3='HKD';
UPDATE static_currencies SET cu_name_sv='Lempira', cu_sub_name_sv='' WHERE cu_iso_3='HNL';
UPDATE static_currencies SET cu_name_sv='Kuna', cu_sub_name_sv='' WHERE cu_iso_3='HRK';
UPDATE static_currencies SET cu_name_sv='Gourde', cu_sub_name_sv='' WHERE cu_iso_3='HTG';
UPDATE static_currencies SET cu_name_sv='Forint', cu_sub_name_sv='' WHERE cu_iso_3='HUF';
UPDATE static_currencies SET cu_name_sv='Rupiah', cu_sub_name_sv='' WHERE cu_iso_3='IDR';
UPDATE static_currencies SET cu_name_sv='Shekel', cu_sub_name_sv='' WHERE cu_iso_3='ILS';
UPDATE static_currencies SET cu_name_sv='Indisk rupee', cu_sub_name_sv='' WHERE cu_iso_3='INR';
UPDATE static_currencies SET cu_name_sv='Irakisk dinar', cu_sub_name_sv='' WHERE cu_iso_3='IQD';
UPDATE static_currencies SET cu_name_sv='Iransk rial', cu_sub_name_sv='' WHERE cu_iso_3='IRR';
UPDATE static_currencies SET cu_name_sv='Isländsk krona', cu_sub_name_sv='' WHERE cu_iso_3='ISK';
UPDATE static_currencies SET cu_name_sv='Jamaicansk dollar', cu_sub_name_sv='' WHERE cu_iso_3='JMD';
UPDATE static_currencies SET cu_name_sv='Jordansk dinar', cu_sub_name_sv='' WHERE cu_iso_3='JOD';
UPDATE static_currencies SET cu_name_sv='Yen', cu_sub_name_sv='' WHERE cu_iso_3='JPY';
UPDATE static_currencies SET cu_name_sv='Kenyansk shilling', cu_sub_name_sv='' WHERE cu_iso_3='KES';
UPDATE static_currencies SET cu_name_sv='Kirgizistansk som', cu_sub_name_sv='' WHERE cu_iso_3='KGS';
UPDATE static_currencies SET cu_name_sv='Riel', cu_sub_name_sv='' WHERE cu_iso_3='KHR';
UPDATE static_currencies SET cu_name_sv='Komoransk franc', cu_sub_name_sv='' WHERE cu_iso_3='KMF';
UPDATE static_currencies SET cu_name_sv='Nordkoreansk won', cu_sub_name_sv='' WHERE cu_iso_3='KPW';
UPDATE static_currencies SET cu_name_sv='Sydkoreansk won', cu_sub_name_sv='' WHERE cu_iso_3='KRW';
UPDATE static_currencies SET cu_name_sv='Kuwaitisk dinar', cu_sub_name_sv='' WHERE cu_iso_3='KWD';
UPDATE static_currencies SET cu_name_sv='Caymansk dollar', cu_sub_name_sv='' WHERE cu_iso_3='KYD';
UPDATE static_currencies SET cu_name_sv='Tenge', cu_sub_name_sv='' WHERE cu_iso_3='KZT';
UPDATE static_currencies SET cu_name_sv='Kip', cu_sub_name_sv='' WHERE cu_iso_3='LAK';
UPDATE static_currencies SET cu_name_sv='Libanesiskt pund', cu_sub_name_sv='' WHERE cu_iso_3='LBP';
UPDATE static_currencies SET cu_name_sv='Lankesisk rupee', cu_sub_name_sv='' WHERE cu_iso_3='LKR';
UPDATE static_currencies SET cu_name_sv='Liberisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='LRD';
UPDATE static_currencies SET cu_name_sv='Loti', cu_sub_name_sv='' WHERE cu_iso_3='LSL';
UPDATE static_currencies SET cu_name_sv='Litas', cu_sub_name_sv='' WHERE cu_iso_3='LTL';
UPDATE static_currencies SET cu_name_sv='Lats', cu_sub_name_sv='' WHERE cu_iso_3='LVL';
UPDATE static_currencies SET cu_name_sv='Libysk dinar', cu_sub_name_sv='' WHERE cu_iso_3='LYD';
UPDATE static_currencies SET cu_name_sv='Marockansk dirham', cu_sub_name_sv='' WHERE cu_iso_3='MAD';
UPDATE static_currencies SET cu_name_sv='Moldavisk leu', cu_sub_name_sv='' WHERE cu_iso_3='MDL';
UPDATE static_currencies SET cu_name_sv='Ariary', cu_sub_name_sv='' WHERE cu_iso_3='MGA';
UPDATE static_currencies SET cu_name_sv='Makedonisk denar', cu_sub_name_sv='' WHERE cu_iso_3='MKD';
UPDATE static_currencies SET cu_name_sv='Kyat', cu_sub_name_sv='' WHERE cu_iso_3='MMK';
UPDATE static_currencies SET cu_name_sv='Tögrög', cu_sub_name_sv='' WHERE cu_iso_3='MNT';
UPDATE static_currencies SET cu_name_sv='Pataca', cu_sub_name_sv='' WHERE cu_iso_3='MOP';
UPDATE static_currencies SET cu_name_sv='Ouguiya', cu_sub_name_sv='' WHERE cu_iso_3='MRO';
UPDATE static_currencies SET cu_name_sv='Mauritisk rupie', cu_sub_name_sv='' WHERE cu_iso_3='MUR';
UPDATE static_currencies SET cu_name_sv='Rufiyah', cu_sub_name_sv='' WHERE cu_iso_3='MVR';
UPDATE static_currencies SET cu_name_sv='malawisk kwacha', cu_sub_name_sv='' WHERE cu_iso_3='MWK';
UPDATE static_currencies SET cu_name_sv='Mexikansk peso', cu_sub_name_sv='' WHERE cu_iso_3='MXN';
UPDATE static_currencies SET cu_name_sv='Mexican Unidad de Inversion (UDI) (fonder)', cu_sub_name_sv='' WHERE cu_iso_3='MXV';
UPDATE static_currencies SET cu_name_sv='Ringgit', cu_sub_name_sv='' WHERE cu_iso_3='MYR';
UPDATE static_currencies SET cu_name_sv='Metical', cu_sub_name_sv='' WHERE cu_iso_3='MZN';
UPDATE static_currencies SET cu_name_sv='Namibisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='NAD';
UPDATE static_currencies SET cu_name_sv='Naira', cu_sub_name_sv='' WHERE cu_iso_3='NGN';
UPDATE static_currencies SET cu_name_sv='Córdoba', cu_sub_name_sv='' WHERE cu_iso_3='NIO';
UPDATE static_currencies SET cu_name_sv='Norsk krona', cu_sub_name_sv='' WHERE cu_iso_3='NOK';
UPDATE static_currencies SET cu_name_sv='Nepalesisk rupee', cu_sub_name_sv='' WHERE cu_iso_3='NPR';
UPDATE static_currencies SET cu_name_sv='Nyzeeländsk dollar', cu_sub_name_sv='' WHERE cu_iso_3='NZD';
UPDATE static_currencies SET cu_name_sv='Omansk rial', cu_sub_name_sv='' WHERE cu_iso_3='OMR';
UPDATE static_currencies SET cu_name_sv='Balboa', cu_sub_name_sv='' WHERE cu_iso_3='PAB';
UPDATE static_currencies SET cu_name_sv='Nuevo sol', cu_sub_name_sv='' WHERE cu_iso_3='PEN';
UPDATE static_currencies SET cu_name_sv='Kina', cu_sub_name_sv='' WHERE cu_iso_3='PGK';
UPDATE static_currencies SET cu_name_sv='Filippinsk peso', cu_sub_name_sv='' WHERE cu_iso_3='PHP';
UPDATE static_currencies SET cu_name_sv='Pakistansk rupee', cu_sub_name_sv='' WHERE cu_iso_3='PKR';
UPDATE static_currencies SET cu_name_sv='Zloty', cu_sub_name_sv='' WHERE cu_iso_3='PLN';
UPDATE static_currencies SET cu_name_sv='Guarani', cu_sub_name_sv='' WHERE cu_iso_3='PYG';
UPDATE static_currencies SET cu_name_sv='Qatarisk rial', cu_sub_name_sv='' WHERE cu_iso_3='QAR';
UPDATE static_currencies SET cu_name_sv='Rumänsk leu', cu_sub_name_sv='' WHERE cu_iso_3='RON';
UPDATE static_currencies SET cu_name_sv='Serbisk dinar', cu_sub_name_sv='' WHERE cu_iso_3='RSD';
UPDATE static_currencies SET cu_name_sv='Rubel', cu_sub_name_sv='' WHERE cu_iso_3='RUB';
UPDATE static_currencies SET cu_name_sv='Rwandisk franc', cu_sub_name_sv='' WHERE cu_iso_3='RWF';
UPDATE static_currencies SET cu_name_sv='Saudiarabisk rial', cu_sub_name_sv='' WHERE cu_iso_3='SAR';
UPDATE static_currencies SET cu_name_sv='Salomondollar', cu_sub_name_sv='' WHERE cu_iso_3='SBD';
UPDATE static_currencies SET cu_name_sv='Seychellisk rupee', cu_sub_name_sv='' WHERE cu_iso_3='SCR';
UPDATE static_currencies SET cu_name_sv='Sudanesisk pund', cu_sub_name_sv='' WHERE cu_iso_3='SDG';
UPDATE static_currencies SET cu_name_sv='Svensk krona', cu_sub_name_sv='' WHERE cu_iso_3='SEK';
UPDATE static_currencies SET cu_name_sv='Singaporiansk dollar', cu_sub_name_sv='' WHERE cu_iso_3='SGD';
UPDATE static_currencies SET cu_name_sv='Sankthelenskt pund', cu_sub_name_sv='' WHERE cu_iso_3='SHP';
UPDATE static_currencies SET cu_name_sv='Slovakisk krona', cu_sub_name_sv='' WHERE cu_iso_3='SKK';
UPDATE static_currencies SET cu_name_sv='Leone', cu_sub_name_sv='' WHERE cu_iso_3='SLL';
UPDATE static_currencies SET cu_name_sv='Somalisk shilling', cu_sub_name_sv='' WHERE cu_iso_3='SOS';
UPDATE static_currencies SET cu_name_sv='Surinamesisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='SRD';
UPDATE static_currencies SET cu_name_sv='Dobra', cu_sub_name_sv='' WHERE cu_iso_3='STD';
UPDATE static_currencies SET cu_name_sv='Syriskt pund', cu_sub_name_sv='' WHERE cu_iso_3='SYP';
UPDATE static_currencies SET cu_name_sv='Lilangeni', cu_sub_name_sv='' WHERE cu_iso_3='SZL';
UPDATE static_currencies SET cu_name_sv='Baht', cu_sub_name_sv='' WHERE cu_iso_3='THB';
UPDATE static_currencies SET cu_name_sv='Somoni', cu_sub_name_sv='' WHERE cu_iso_3='TJS';
UPDATE static_currencies SET cu_name_sv='Turkmenistansk manat', cu_sub_name_sv='' WHERE cu_iso_3='TMM';
UPDATE static_currencies SET cu_name_sv='Tunisisk dinar', cu_sub_name_sv='' WHERE cu_iso_3='TND';
UPDATE static_currencies SET cu_name_sv='Pa\'anga', cu_sub_name_sv='' WHERE cu_iso_3='TOP';
UPDATE static_currencies SET cu_name_sv='Lira', cu_sub_name_sv='' WHERE cu_iso_3='TRY';
UPDATE static_currencies SET cu_name_sv='Trinidaddollar', cu_sub_name_sv='' WHERE cu_iso_3='TTD';
UPDATE static_currencies SET cu_name_sv='Taiwanesisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='TWD';
UPDATE static_currencies SET cu_name_sv='Tanzanisk shilling', cu_sub_name_sv='' WHERE cu_iso_3='TZS';
UPDATE static_currencies SET cu_name_sv='Hryvnja', cu_sub_name_sv='' WHERE cu_iso_3='UAH';
UPDATE static_currencies SET cu_name_sv='Ugandisk shilling', cu_sub_name_sv='' WHERE cu_iso_3='UGX';
UPDATE static_currencies SET cu_name_sv='United States dollar', cu_sub_name_sv='' WHERE cu_iso_3='USD';
UPDATE static_currencies SET cu_name_sv='United States dollar (nästa dag) (fonder)', cu_sub_name_sv='' WHERE cu_iso_3='USN';
UPDATE static_currencies SET cu_name_sv='United States dollar (samma dag) (fonder)', cu_sub_name_sv='' WHERE cu_iso_3='USS';
UPDATE static_currencies SET cu_name_sv='Uruguayansk peso', cu_sub_name_sv='' WHERE cu_iso_3='UYU';
UPDATE static_currencies SET cu_name_sv='Uzbekistansk som', cu_sub_name_sv='' WHERE cu_iso_3='UZS';
UPDATE static_currencies SET cu_name_sv='Bolívar', cu_sub_name_sv='' WHERE cu_iso_3='VEF';
UPDATE static_currencies SET cu_name_sv='Dong', cu_sub_name_sv='' WHERE cu_iso_3='VND';
UPDATE static_currencies SET cu_name_sv='Vatu', cu_sub_name_sv='' WHERE cu_iso_3='VUV';
UPDATE static_currencies SET cu_name_sv='Tala', cu_sub_name_sv='' WHERE cu_iso_3='WST';
UPDATE static_currencies SET cu_name_sv='CFA-franc (BEAC)', cu_sub_name_sv='' WHERE cu_iso_3='XAF';
UPDATE static_currencies SET cu_name_sv='Silver (en troy ounce)', cu_sub_name_sv='' WHERE cu_iso_3='XAG';
UPDATE static_currencies SET cu_name_sv='Guld (en troy ounce)', cu_sub_name_sv='' WHERE cu_iso_3='XAU';
UPDATE static_currencies SET cu_name_sv='European Composite Unit (EURCO) (enhet använd på obligationsmarknaden)', cu_sub_name_sv='' WHERE cu_iso_3='XBA';
UPDATE static_currencies SET cu_name_sv='European Monetary Unit (E.M.U.-6) (enhet använd på obligationsmarknaden)', cu_sub_name_sv='' WHERE cu_iso_3='XBB';
UPDATE static_currencies SET cu_name_sv='European Unit of Account 9 (E.U.A.-9) (enhet använd på obligationsmarknaden)', cu_sub_name_sv='' WHERE cu_iso_3='XBC';
UPDATE static_currencies SET cu_name_sv='European Unit of Account 17 (E.U.A.-17) (enhet använd på obligationsmarknaden)', cu_sub_name_sv='' WHERE cu_iso_3='XBD';
UPDATE static_currencies SET cu_name_sv='Östkaribisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='XCD';
UPDATE static_currencies SET cu_name_sv='Särskilda dragningsrätter', cu_sub_name_sv='' WHERE cu_iso_3='XDR';
UPDATE static_currencies SET cu_name_sv='UIC franc', cu_sub_name_sv='' WHERE cu_iso_3='XFU';
UPDATE static_currencies SET cu_name_sv='CFA-franc (BCEAO)', cu_sub_name_sv='' WHERE cu_iso_3='XOF';
UPDATE static_currencies SET cu_name_sv='Palladium (en troy ounce)', cu_sub_name_sv='' WHERE cu_iso_3='XPD';
UPDATE static_currencies SET cu_name_sv='CFP-franc', cu_sub_name_sv='' WHERE cu_iso_3='XPF';
UPDATE static_currencies SET cu_name_sv='Platina (en troy ounce)', cu_sub_name_sv='' WHERE cu_iso_3='XPT';
UPDATE static_currencies SET cu_name_sv='Kod reserverad i testningssyfte', cu_sub_name_sv='' WHERE cu_iso_3='XTS';
UPDATE static_currencies SET cu_name_sv='Ingen valuta', cu_sub_name_sv='' WHERE cu_iso_3='XXX';
UPDATE static_currencies SET cu_name_sv='Jemenitisk rial', cu_sub_name_sv='' WHERE cu_iso_3='YER';
UPDATE static_currencies SET cu_name_sv='Rand', cu_sub_name_sv='' WHERE cu_iso_3='ZAR';
UPDATE static_currencies SET cu_name_sv='Zambisk kwacha', cu_sub_name_sv='' WHERE cu_iso_3='ZMK';
UPDATE static_currencies SET cu_name_sv='Zimbabwisk dollar', cu_sub_name_sv='' WHERE cu_iso_3='ZWD';

## static_territories
UPDATE static_territories SET tr_name_no='Afrika' WHERE tr_iso_nr='2';
UPDATE static_territories SET tr_name_no='Oceanien' WHERE tr_iso_nr='9';
UPDATE static_territories SET tr_name_no='Nord-, Sentral- og Sør-Amerika' WHERE tr_iso_nr='19';
UPDATE static_territories SET tr_name_no='Asien' WHERE tr_iso_nr='142';
UPDATE static_territories SET tr_name_no='Europa' WHERE tr_iso_nr='150';
UPDATE static_territories SET tr_name_no='Östasien' WHERE tr_iso_nr='30';
UPDATE static_territories SET tr_name_no='Söröstasien' WHERE tr_iso_nr='35';
UPDATE static_territories SET tr_name_no='0' WHERE tr_iso_nr='143';
UPDATE static_territories SET tr_name_no='Vestasien' WHERE tr_iso_nr='145';
UPDATE static_territories SET tr_name_no='Sydeuropa' WHERE tr_iso_nr='39';
UPDATE static_territories SET tr_name_no='Östeuropa' WHERE tr_iso_nr='151';
UPDATE static_territories SET tr_name_no='Nordeuropa' WHERE tr_iso_nr='154';
UPDATE static_territories SET tr_name_no='Vesteuropa' WHERE tr_iso_nr='155';
UPDATE static_territories SET tr_name_no='Sydamerika' WHERE tr_iso_nr='5';
UPDATE static_territories SET tr_name_no='Cantralamerika' WHERE tr_iso_nr='13';
UPDATE static_territories SET tr_name_no='Nordamerika' WHERE tr_iso_nr='21';
UPDATE static_territories SET tr_name_no='Karibien' WHERE tr_iso_nr='29';
UPDATE static_territories SET tr_name_no='Vestafrika' WHERE tr_iso_nr='11';
UPDATE static_territories SET tr_name_no='Östafrika' WHERE tr_iso_nr='14';
UPDATE static_territories SET tr_name_no='Nordafrika' WHERE tr_iso_nr='15';
UPDATE static_territories SET tr_name_no='Centralafrika' WHERE tr_iso_nr='17';
UPDATE static_territories SET tr_name_no='Sydafrika' WHERE tr_iso_nr='18';
UPDATE static_territories SET tr_name_no='Australien og New Zealand' WHERE tr_iso_nr='53';
UPDATE static_territories SET tr_name_no='Melanesien' WHERE tr_iso_nr='54';
UPDATE static_territories SET tr_name_no='Mikronesien' WHERE tr_iso_nr='57';
UPDATE static_territories SET tr_name_no='Polynesien' WHERE tr_iso_nr='61';
UPDATE static_territories SET tr_name_no='0' WHERE tr_iso_nr='34';

##static countries
UPDATE static_countries SET cn_short_sv='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_sv='Förenade arabemiraten' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_sv='Afghanistan' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_sv='Antigua och Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_sv='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_sv='Albanien' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_sv='Armenien' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_sv='Nederländska Antillerna' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_sv='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_sv='Antarktis' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_sv='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_sv='Amerikanska Samoa' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_sv='Österrike' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_sv='Australien' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_sv='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_sv='Åland' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_sv='Azerbajdzjan' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_sv='Bosnien-Hercegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_sv='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_sv='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_sv='Belgien' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_sv='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_sv='Bulgarien' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_sv='Bahrain' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_sv='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_sv='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_sv='Bermuda' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_sv='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_sv='Bolivia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_sv='Brasilien' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_sv='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_sv='Bhutan' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_sv='Bouvetön' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_sv='Botswana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_sv='Vitryssland' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_sv='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_sv='Kanada' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_sv='Kokosöarna' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_sv='Centralafrikanska republiken' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_sv='Kongo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_sv='Schweiz' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_sv='Elfenbenskusten' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_sv='Cooköarna' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_sv='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_sv='Kamerun' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_sv='Kina' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_sv='Colombia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_sv='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_sv='Kuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_sv='Kap Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_sv='Julön' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_sv='Cypern' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_sv='Tjeckien' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_sv='Tyskland' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_sv='Djibouti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_sv='Danmark' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_sv='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_sv='Dominikanska republiken' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_sv='Algeriet' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_sv='Ecuador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_sv='Estland' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_sv='Egypten' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_sv='Västsahara' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_sv='Eritrea' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_sv='Spanien' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_sv='Etiopien' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_sv='Finland' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_sv='Fiji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_sv='Falklandsöarna' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_sv='Mikronesiens federerade stater' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_sv='Färöarna' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_sv='Frankrike' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_sv='France métropolitaine (Frankrike, europeiska delen)' WHERE cn_iso_2='FX';
UPDATE static_countries SET cn_short_sv='Gabon' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_sv='Storbritannien' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_sv='Grenada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_sv='Georgien' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_sv='Franska Guyana' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_sv='Ghana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_sv='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_sv='Grönland' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_sv='Gambia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_sv='Guinea' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_sv='Guadeloupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_sv='Ekvatorialguinea' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_sv='Grekland' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_sv='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_sv='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_sv='Guinea Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_sv='Guyana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_sv='Hongkong' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_sv='Heard- och McDonaldsöarna' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_sv='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_sv='Kroatien' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_sv='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_sv='Ungern' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_sv='Indonesien' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_sv='Irland' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_sv='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_sv='Indien' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_sv='Brittiska territoriet i Indiska Oceanen' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_sv='Irak' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_sv='Iran' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_sv='Island' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_sv='Italien' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_sv='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_sv='Jordanien' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_sv='Japan' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_sv='Kenya' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_sv='Kirgizistan' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_sv='Kambodja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_sv='Kiribati' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_sv='Comorerna' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_sv='Saint Kitts och Nevis' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_sv='Nordkorea' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_sv='Sydkorea' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_sv='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_sv='Caymanöarna' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_sv='Kazakstan' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_sv='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_sv='Libanon' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_sv='Saint Lucia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_sv='Liechtenstein' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_sv='Sri Lanka' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_sv='Liberia' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_sv='Lesotho' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_sv='Litauen' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_sv='Luxemburg' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_sv='Lettland' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_sv='Libyen' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_sv='Marocko' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_sv='Monaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_sv='Moldavien' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_sv='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_sv='Madagaskar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_sv='Marshallöarna' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_sv='Makedonien' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_sv='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_sv='Burma (Myanmar)' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_sv='Mongoliet' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_sv='Macau' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_sv='Nordmarianerna' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_sv='Martinique' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_sv='Mauretanien' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_sv='Montserrat' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_sv='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_sv='Mauritius' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_sv='Maldiverna' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_sv='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_sv='Mexiko' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_sv='Malaysia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_sv='Moçambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_sv='Namibia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_sv='Nya Kaledonien' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_sv='Niger' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_sv='Norfolkön' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_sv='Nigeria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_sv='Nicaragua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_sv='Nederländerna' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_sv='Norge' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_sv='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_sv='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_sv='Niue' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_sv='Nya Zeeland' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_sv='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_sv='Panama' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_sv='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_sv='Franska Polynesien' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_sv='Papua Nya Guinea' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_sv='Filippinerna' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_sv='Pakistan' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_sv='Polen' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_sv='Saint Pierre och Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_sv='Pitcairn' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_sv='Puerto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_sv='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_sv='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_sv='Paraguay' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_sv='Qatar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_sv='Reunion' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_sv='Rumänien' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_sv='Serbien' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_sv='Ryssland' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_sv='Rwanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_sv='Saudiarabien' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_sv='Salomonöarna' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_sv='Seychellerna' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_sv='Sudan' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_sv='Sverige' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_sv='Singapore' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_sv='Sankta Helena' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_sv='Slovenien' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_sv='Svalbard och Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_sv='Slovakien' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_sv='Sierra Leone' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_sv='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_sv='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_sv='Somalia' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_sv='Surinam' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_sv='São Tomé och Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_sv='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_sv='Syrien' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_sv='Swaziland' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_sv='Turks och Caicosöarna' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_sv='Tchad' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_sv='Franska södra territorierna' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_sv='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_sv='Thailand' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_sv='Tadzjikistan' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_sv='Tokelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_sv='Turkmenistan' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_sv='Tunisien' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_sv='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_sv='Östtimor' WHERE cn_iso_2='TP';
UPDATE static_countries SET cn_short_sv='Turkiet' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_sv='Trinidad och Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_sv='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_sv='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_sv='Tanzania' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_sv='Ukraina' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_sv='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_sv='USA:s yttre öar' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_sv='USA' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_sv='Uruguay' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_sv='Uzbekistan' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_sv='Vatikanstaten' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_sv='Saint Vincent och Grenadinerna' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_sv='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_sv='Brittiska Jungfruöarna' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_sv='ISO 3166-2:VI' WHERE cn_iso_2='VI 	VIR';
UPDATE static_countries SET cn_short_sv='Vietnam' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_sv='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_sv='Wallis- och Futunaöarna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_sv='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_sv='Yemen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_sv='Mayotte' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_sv='Sydafrika' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_sv='Zambia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_sv='Zaire' WHERE cn_iso_2='ZR';
UPDATE static_countries SET cn_short_sv='Zimbabwe' WHERE cn_iso_2='ZW';

##static languages
UPDATE static_languages SET lg_name_sv='Afar' WHERE lg_iso_2='AA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Abchaziska' WHERE lg_iso_2='AB' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Afrikaans' WHERE lg_iso_2='AF' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Amhariska' WHERE lg_iso_2='AM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Arabiska' WHERE lg_iso_2='AR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Assamesiska' WHERE lg_iso_2='AS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Aymara' WHERE lg_iso_2='AY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Azerbajdzjanska' WHERE lg_iso_2='AZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Basjkiriska' WHERE lg_iso_2='BA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Vitryska' WHERE lg_iso_2='BE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Bulgariska' WHERE lg_iso_2='BG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Bihari' WHERE lg_iso_2='BH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Bislama' WHERE lg_iso_2='BI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Bengali' WHERE lg_iso_2='BN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tibetanska' WHERE lg_iso_2='BO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Bretonska' WHERE lg_iso_2='BR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Katalanska' WHERE lg_iso_2='CA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Korsikanska' WHERE lg_iso_2='CO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tjeckiska' WHERE lg_iso_2='CS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kymriska' WHERE lg_iso_2='CY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Danska' WHERE lg_iso_2='DA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tyska' WHERE lg_iso_2='DE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tibetanska (dzhongkha)' WHERE lg_iso_2='DZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Grekiska' WHERE lg_iso_2='EL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Engelska' WHERE lg_iso_2='EN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Esperanto' WHERE lg_iso_2='EO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Spanska' WHERE lg_iso_2='ES' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Estniska' WHERE lg_iso_2='ET' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Baskiska' WHERE lg_iso_2='EU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Persiska (farsi)' WHERE lg_iso_2='FA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Finska' WHERE lg_iso_2='FI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Fiji' WHERE lg_iso_2='FJ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Färöiska' WHERE lg_iso_2='FO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Franska' WHERE lg_iso_2='FR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Frisiska' WHERE lg_iso_2='FY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Iriska' WHERE lg_iso_2='GA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Gaeliska' WHERE lg_iso_2='GD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Galiciska' WHERE lg_iso_2='GL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Guarani' WHERE lg_iso_2='GN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Gujarati' WHERE lg_iso_2='GU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Hausa' WHERE lg_iso_2='HA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Hebreiska' WHERE lg_iso_2='HE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Hindi' WHERE lg_iso_2='HI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kroatiska' WHERE lg_iso_2='HR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Ungerska' WHERE lg_iso_2='HU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Armeniska' WHERE lg_iso_2='HY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Interlingua' WHERE lg_iso_2='IA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Indonesiska' WHERE lg_iso_2='ID' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Interlingue' WHERE lg_iso_2='IE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Inupiak' WHERE lg_iso_2='IK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Indonesiska' WHERE lg_iso_2='IN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Isländska' WHERE lg_iso_2='IS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Italienska' WHERE lg_iso_2='IT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Inuktitut' WHERE lg_iso_2='IU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Hebreiska' WHERE lg_iso_2='IW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Japanska' WHERE lg_iso_2='JA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Jiddisch' WHERE lg_iso_2='JI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Javanesiska' WHERE lg_iso_2='JV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Georgiska' WHERE lg_iso_2='KA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kazakiska' WHERE lg_iso_2='KK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Grönländska' WHERE lg_iso_2='KL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kambodjanska' WHERE lg_iso_2='KM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kannada' WHERE lg_iso_2='KN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Koreanska' WHERE lg_iso_2='KO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kashmiri' WHERE lg_iso_2='KS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kurdiska' WHERE lg_iso_2='KU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kirgiziska' WHERE lg_iso_2='KY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Latin' WHERE lg_iso_2='LA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Lingala' WHERE lg_iso_2='LN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Laotiska' WHERE lg_iso_2='LO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Litauiska' WHERE lg_iso_2='LT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Lettiska' WHERE lg_iso_2='LV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Madagaskiska' WHERE lg_iso_2='MG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Maori' WHERE lg_iso_2='MI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Makedonska' WHERE lg_iso_2='MK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Malayalam' WHERE lg_iso_2='ML' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Mongoliska' WHERE lg_iso_2='MN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Moldaviska' WHERE lg_iso_2='MO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Marathi' WHERE lg_iso_2='MR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Malajiska' WHERE lg_iso_2='MS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Maltesiska' WHERE lg_iso_2='MT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Burmesiska' WHERE lg_iso_2='MY' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Nauriska' WHERE lg_iso_2='NA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Nepali' WHERE lg_iso_2='NE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Nederländska' WHERE lg_iso_2='NL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Norska' WHERE lg_iso_2='NO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Occitanska' WHERE lg_iso_2='OC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Afan oromo' WHERE lg_iso_2='OM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Oriya' WHERE lg_iso_2='OR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Punjabi' WHERE lg_iso_2='PA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Polska' WHERE lg_iso_2='PL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Pashto' WHERE lg_iso_2='PS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Portugisiska' WHERE lg_iso_2='PT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Quechua' WHERE lg_iso_2='QU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Rätoromanska' WHERE lg_iso_2='RM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kirundi' WHERE lg_iso_2='RN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Rumänska' WHERE lg_iso_2='RO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Ryska' WHERE lg_iso_2='RU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kinyarwanda' WHERE lg_iso_2='RW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Sanskrit' WHERE lg_iso_2='SA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Sardiska' WHERE lg_iso_2='SC' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Sindhi' WHERE lg_iso_2='SD' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Sangho' WHERE lg_iso_2='SG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Serbokroatiska' WHERE lg_iso_2='SH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Singalesiska' WHERE lg_iso_2='SI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Slovakiska' WHERE lg_iso_2='SK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Slovenska' WHERE lg_iso_2='SL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Samoanska' WHERE lg_iso_2='SM' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Shona' WHERE lg_iso_2='SN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Somaliska' WHERE lg_iso_2='SO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Albanska' WHERE lg_iso_2='SQ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Serbiska' WHERE lg_iso_2='SR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Siswati' WHERE lg_iso_2='SS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Sesotho' WHERE lg_iso_2='ST' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Sundanesiska' WHERE lg_iso_2='SU' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Svenska' WHERE lg_iso_2='SV' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Swahili' WHERE lg_iso_2='SW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tamil' WHERE lg_iso_2='TA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Telugu' WHERE lg_iso_2='TE' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tadzjikiska' WHERE lg_iso_2='TG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Thailändska' WHERE lg_iso_2='TH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tigrinja' WHERE lg_iso_2='TI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Turkmenska' WHERE lg_iso_2='TK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tagalog' WHERE lg_iso_2='TL' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Setswana' WHERE lg_iso_2='TN' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tonganska' WHERE lg_iso_2='TO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Turkiska' WHERE lg_iso_2='TR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tsonga' WHERE lg_iso_2='TS' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Tatariska' WHERE lg_iso_2='TT' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Twi' WHERE lg_iso_2='TW' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Uiguriska' WHERE lg_iso_2='UG' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Ukrainska' WHERE lg_iso_2='UK' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Urdu' WHERE lg_iso_2='UR' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Uzbekiska' WHERE lg_iso_2='UZ' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Vietnamesiska' WHERE lg_iso_2='VI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Volapük' WHERE lg_iso_2='VO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Wolof' WHERE lg_iso_2='WO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Xhosa' WHERE lg_iso_2='XH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Jiddisch' WHERE lg_iso_2='YI' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Yoruba' WHERE lg_iso_2='YO' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Zhuang' WHERE lg_iso_2='ZA' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Kinesiska' WHERE lg_iso_2='ZH' AND LG_COUNTRY_ISO_2='';
UPDATE static_languages SET lg_name_sv='Zulu' WHERE lg_iso_2='ZU' AND LG_COUNTRY_ISO_2='';